name: build-base-image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  BASE_IMAGE: uriacan/yaish-openhedex:config-fork
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t $BASE_IMAGE .
    - run: docker push $BASE_IMAGE
    - run: echo image built - $BASE_IMAGE
